# ~/.config/alacritty/alacritty.toml

[window.dimensions]
columns = 135
lines = 35

[font.normal]
family = "JetBrains Mono"
#family = "JetBrainsMono Nerd Font"
style = "Regular"

# Japanesque from https://gogh-co.github.io/Gogh/
[colors.primary]
foreground = "#F7F6EC"
background = "#1E1E1E"

[colors.normal]
black = "#343935"
red = "#CF3F61"
green = "#7BB75B"
yellow = "#E9B32A"
blue = "#4C9AD4"
magenta = "#A57FC4"
cyan = "#389AAD"
white = "#FAFAF6"

[colors.bright]
black = "#595B59"
red = "#D18FA6"
green = "#767F2C"
yellow = "#78592F"
blue = "#135979"
magenta = "#604291"
cyan = "#76BBCA"
white = "#B2B5AE"
